# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170921_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='first_app.Note'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='participants',
            field=models.ManyToManyField(default=None, related_name='joined_trips', to='first_app.User'),
        ),
    ]
